### PR TITLE
Memory Pool

### PR DESCRIPTION
**Pull request by luoyetx**
This PR implement strategy-1 mentioned in #29 . Memory usage of example r-fcn can be reduced from 2G to 500MB on CPU context and from 1.8G to 600M on GPU context (with CUDNN).

Some works still need to be done.

1. impl a small object pool to hold data shapes, which usually < 128 bytes.
2. test on fully convolution network, current pool strategy borrow memory to blob only if requested memory size >= half of real memory size. This may cause memory issue when using fully convolution network.

### CODE REVIEW

**Comment by luoyetx** [comment]
Improve the memory usage also speed up network forward. Example r-fcn speed up ~100ms on my GTX 960.

**Comment by luoyetx** [comment]
current memory pool is not friend to network who's size varies during every forward. This includes fully convolution network and network uses different batch size. Red line indicts the total memory allocate on the pool, Blue line represents the memory network really uses. The pattern is kind of stable, maybe some simple strategy can handle this situation.

bfconv

This is the biggest disadvantage of dynamic memory plan, the memory may not be fully utilized but this simple strategy is easy to implement and does well on most situation. I think static memory plan can handle this problem very well but it's hard to implement and will modifies codebase much.

**Comment by luoyetx** [comment]
repeatly run example R-FCN network.

rfcn

**Comment by luoyetx** [comment]
merge it PR for now, more memory analyse will be open in another PR.

**Comment by liyancas** [comment]
"test on fully convolution network, current pool strategy borrow memory to blob only if requested memory size >= half of real memory size. **This may cause memory issue when using fully convolution network**."  Could you show an example about this issue?

**Comment by luoyetx** [comment]
@liyancas view the analyse above. The first graph is from networks which take input with various size (including batch size, height and width). The second is from a network running repeatedly on the same input data.

Currently, there's an API I add that can clear memory pool. Calling this API after every inference can solve the memory problem.

**Pull request merged**
